### ISSUE TITLE
ReferenceError: events is not defined

### ISSUE THREAD

**Issue by zoski** [derbl4ck/jc3mp-developerView#1]
Got this problem at server launch. Doing a `restart_package` give the same error.
```
/home/steam/steamcmd/jc3mp-public2/packages/devview/main.js:12
events.AddRemoteCallable('developerview_addDrawcall', (pkg, title, value) => {
^

ReferenceError: events is not defined
    at Object.<anonymous> (/home/steam/steamcmd/jc3mp-public2/packages/devview/main.js:12:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by derbl4ck** [comment]
Yeah, I forgot to update the package. Should be fixed in v0.0.2 ( https://github.com/derbl4ck/jc3mp-developerView/commit/050f1220c37e0515cded65edeac7d1159550a04e )
